services:
  backend:
    build:
      context: ./backend
    container_name: backendSHA
    ports:
     - "3000:3000"
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=232332321
      - DATABASE_NAME=laba3
    networks:
      - app-network
  
  frontend:
    build:
      context: ./frontend
    container_name: frontendSHA
    ports:
     - "8080:8080"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: yarn serve
    networks:
      - app-network

  database:
    image: postgres:13
    container_name: postgresSHA
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 232332321
      POSTGRES_DB: laba3
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
